services:
  - type: web
    name: opportunity-bot-api
    env: python
    region: oregon  # or "frankfurt", "singapore", etc.
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHANNEL_ID
        sync: false
      - key: DB_PATH
        value: data/opportunities.db
    autoDeploy: true

  - type: cron
    name: daily-scraper
    env: python
    schedule: "0 6 * * *"  # Every day at 6:00 AM UTC
    command: python app/scraper.py
    envVars:
      - key: DB_PATH
        value: data/opportunities.db
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHANNEL_ID
        sync: false
