services:
  - type: web
    name: opportunity-scraper-web
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: DATABASE_URL
        value: your-postgres-url-here
      - key: TELEGRAM_BOT_TOKEN
        value: your-bot-token
      - key: TELEGRAM_CHANNEL_ID
        value: your-channel-id

  - type: worker
    name: opportunity-scraper-worker
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app/worker.py"
    envVars:
      - key: DATABASE_URL
        value: your-postgres-url-here
      - key: TELEGRAM_BOT_TOKEN
        value: your-bot-token
      - key: TELEGRAM_CHANNEL_ID
        value: your-channel-id
