"""initial_tables

Revision ID: e8d62ed31231
Revises: 
Create Date: 2026-06-26 03:35:56.374977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8d62ed31231'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_admins',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('added_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('invite_tokens',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deadline', sa.String(), nullable=True),
    sa.Column('thumbnail', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('posted_to_telegram', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link')
    )
    op.create_index('idx_created_at', 'opportunities', ['created_at'], unique=False)
    op.create_index('idx_posted_to_telegram', 'opportunities', ['posted_to_telegram'], unique=False)
    op.create_index(op.f('ix_opportunities_id'), 'opportunities', ['id'], unique=False)
    op.create_table('pending_admins',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('pending_schedule_input',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('input_type', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('schedule_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_str', sa.String(length=5), nullable=False),
    sa.Column('schedule_type', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_times_id'), 'schedule_times', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_times_id'), table_name='schedule_times')
    op.drop_table('schedule_times')
    op.drop_table('pending_schedule_input')
    op.drop_table('pending_admins')
    op.drop_index(op.f('ix_opportunities_id'), table_name='opportunities')
    op.drop_index('idx_posted_to_telegram', table_name='opportunities')
    op.drop_index('idx_created_at', table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_table('invite_tokens')
    op.drop_table('bot_admins')
    # ### end Alembic commands ###
